//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::episodes::Entity as Episodes;
pub use super::movies::Entity as Movies;
pub use super::seasons::Entity as Seasons;
pub use super::series::Entity as Series;
pub use super::tvs::Entity as Tvs;
pub use super::users::Entity as Users;
